[package]
name = "docker-actix-sqlx"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "server"

[dependencies]
actix-web = "3"
dotenv = "0.15"

[dependencies.sqlx]
version = "0.4"
features = [
    "runtime-actix-rustls",
    "postgres",
    "chrono",
    "offline"
]
