version: "3"

services:
  db:
    container_name: postgresql
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: api-server
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: postgres://postgres:password@postgresql:5432/test
    command: server
    links:
      - db

volumes:
  db-data:
